spring.application.name=bff-viacep
server.port=9080

# Redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=Senha@123

spring.cache.type=redis
bff-viacep.redis.ttl.seconds=86400

viacep.url=https://viacep.com.br/ws